### ISSUE TITLE
.nearBy(lat, lon, distance) Question

### ISSUE THREAD

**Issue by waedbara** [strikeentco/geo-nearby#6]
Hello,I want to ask if .`nearBy(lat, lon, distance)` syntax right or[ .nearBy(lon, lat, distance)  ](url)because I try it the second option matched with online difference https://gps-coordinates.org/distance-between-coordinates.php ? solved it depend on arrange coordinates on dataSet.

**Comment by strikeentco** [comment]
I'm closing this issue for now, since you have already solved it by yourself :)

Feel free to open a new one if you have another question or suggestion.
